package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* 17 February 2021 18:32:09 o'clock GMT
*/

public interface HelloOperations 
{
  int sayHello ();
} // interface HelloOperations
